<?php

	//application details
		$apps[$x]['name'] = "Sessiontalk";
		$apps[$x]['uuid'] = "85774108-716c-46cb-a34b-ce80b212bc82";
		$apps[$x]['category'] = "Vendor";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "";
		$apps[$x]['description']['en-gb'] = "";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//permission details
	$y=0;
	$apps[$x]['permissions'][$y]['name'] = "sessiontalk_view";
	$apps[$x]['permissions'][$y]['groups'][] = "user";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "sessiontalk_view_all";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;


	

//default settings
	$y=0;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "67d5e1a7-d0b1-4f3a-b329-fabfb235b0c3";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "provider_id";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk Provider ID - Leave blank for whitelabel apps";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f90a2cd2-55e3-42bf-a6b5-8c9db28ecc9b";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "transport";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "udp";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk Transport. Enable to set default Transport type for Sessiontalk devices.";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "432d9632-eafd-43ef-8955-3a510504c83f";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "srtp";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "Disabled";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk SRTP";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6e9fcc70-d55c-4e73-b331-d4ddad20de69";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "video";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "Disabled";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk Video Support";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4a221416-630c-40f4-967e-85a51d0eb13b";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "messaging";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "Disabled";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk SMS over SIP SIMPLE";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b45b17c9-f1b6-45cf-8996-51ea668d3e9d";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "callrecording";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "Disabled";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk in app call recording";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1104ce84-a9fa-4b65-8376-c9990b40a41c";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "max_activations";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Sessiontalk Maximum Apps per Extension. Defaults to 1 if not set, 0 for unlimited.";
	$y++;		
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6dbdeca0-131f-11eb-adc1-0242ac120002";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "qr_expiration";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "172800";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "QR Code is valid for this many seconds after being generated";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "14b71058-9361-43fd-9f0c-8a08876c7835";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "key_rotation";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "2592000";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Rotation Period of keys. must be greater than the qr expiration period. If you reduce this you may invalidate some keys that have already been generated.";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1af0c0f9-f19d-4f93-ad75-a5a5100d29c8";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "windows_softphone";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable generating the Link to activate the Windows Softphone";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8e38ad32-b124-4793-92a5-7f09478dfa51";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "windows_softphone_url";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "https://windows-softphone.s3.eu-west-2.amazonaws.com/sessioncloud.appxbundle";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "URL for the Windows softphone app. Default is the generic, update if you have a whitelabel app";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2a07baa3-bf07-44a3-b9de-33f350a0e8b6";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "windows_softphone_version";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "1.0.67.0";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Version Number for the sessioncloud .appxbundle. It must match the bundle referenced in the softphone url.";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4794ea27-df93-4e75-8250-6cc96ffb9c60";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "windows_softphone_name";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "SessionCloud";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "File name for the .appinstaller file. Not usually seen by the end user unless they go out of their way to download the file instead of clicking the link";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3c3af619-2e7f-47bf-b37b-5b842150ea18";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "android_url";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "https://play.google.com/store/apps/details?id=co.froute.sessioncloud";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "URL for the Android softphone app. Default is the generic, update if you have a whitelabel app";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ccc31e3b-1384-4e2b-bee0-e69aea7e0c8e";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "sessiontalk";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "apple_url";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "https://apps.apple.com/us/app/sessioncloud-sip-softphone/id1065327562";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "URL for the Apple softphone app. Default is the generic, update if you have a whitelabel app";
	$y++;
	
// schema details
	$y = 0; //table array index
	$z = 0; //field array index
	//Track Keys
	$apps[$x]['db'][$y]['table']['name'] = "v_sessiontalk_keys";
	$apps[$x]['db'][$y]['table']['parent'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "sessiontalk_key_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "key1";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "key2";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "expiration_date";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;

?>
